security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    #voir cette classe pour la manière moderne de gérer la sécurité
                    - App\Security\AppAuthenticator
            logout:
                path: security_logout
                target: home

    role_hierarchy:
        # nos admins ont tous les pouvoirs des users
        ROLE_ADMIN: ROLE_USER

    access_control:
        # premièrement, on autorise l'accès au login pour tout le monde !
        - { path: ^/connexion$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # idem pour l'oubli du mot de passe, si ça commence par ici du coup...
        - { path: ^/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # ensuite, on autorise l'accès au back-office seulement pour les admins
        - { path: ^/admin, roles: ROLE_ADMIN }
        # finalement, on autorise l'accès au site seulement pour les users connectés
        - { path: ^/, roles: ROLE_USER }
